// src/lib/ryanData.js
// Ryan Groene's real race history — single source of truth across all pages

export const RYAN_RACES = [
  {
    id: 1,
    distance: '10K',
    name: "Sole of the City 10K",
    location: 'Baltimore, MD',
    city: 'Baltimore',
    state: 'MD',
    month: 'Oct',
    year: '2021',
    date: 'October 16, 2021',
    time: '47:49',
    pace: '7:42/mi',
    place: null,
    elevation: '—',
    weather: null,
    pr: true,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&h=300&fit=crop',
  },
  {
    id: 2,
    distance: '10K',
    name: 'Bay Bridge Run',
    location: 'Annapolis, MD',
    city: 'Annapolis',
    state: 'MD',
    month: 'Nov',
    year: '2021',
    date: 'November 7, 2021',
    time: '50:57',
    pace: '8:12/mi',
    place: null,
    elevation: '—',
    weather: null,
    pr: false,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&h=300&fit=crop',
  },
  {
    id: 3,
    distance: '10K',
    name: 'Baltimore Running Festival 10K',
    location: 'Baltimore, MD',
    city: 'Baltimore',
    state: 'MD',
    month: 'Oct',
    year: '2021',
    date: 'October 9, 2021',
    time: '58:03',
    pace: '9:21/mi',
    place: null,
    elevation: '—',
    weather: null,
    pr: false,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&h=300&fit=crop',
  },
  {
    id: 4,
    distance: '13.1',
    name: 'Holiday Half Marathon',
    location: 'Annandale, VA',
    city: 'Annandale',
    state: 'VA',
    month: 'Dec',
    year: '2021',
    date: 'December 4, 2021',
    time: '2:19:05',
    pace: '10:37/mi',
    place: null,
    elevation: '—',
    weather: null,
    pr: false,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1540837221-ce4b64fa7c95?w=400&h=300&fit=crop',
  },
  {
    id: 5,
    distance: '26.2',
    name: 'Marine Corps Marathon',
    location: 'Washington, DC',
    city: 'Washington',
    state: 'DC',
    month: 'Oct',
    year: '2023',
    date: 'October 22, 2023',
    time: '4:45:42',
    pace: '10:55/mi',
    place: null,
    elevation: '900ft',
    weather: null,
    pr: false,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1578037970687-42b0e2d8d553?w=400&h=300&fit=crop',
  },
  {
    id: 6,
    distance: '26.2',
    name: 'LA Marathon',
    location: 'Los Angeles, CA',
    city: 'Los Angeles',
    state: 'CA',
    month: 'Mar',
    year: '2023',
    date: 'March 19, 2023',
    time: '4:44:47',
    pace: '10:53/mi',
    place: null,
    elevation: '700ft',
    weather: null,
    pr: true,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=400&h=300&fit=crop',
  },
  {
    id: 7,
    distance: '5K',
    name: 'Downtown Columbia Turkey Trot',
    location: 'Columbia, MD',
    city: 'Columbia',
    state: 'MD',
    month: 'Nov',
    year: '2024',
    date: 'November 28, 2024',
    time: '28:16',
    pace: '9:06/mi',
    place: null,
    elevation: '—',
    weather: null,
    pr: true,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=400&h=300&fit=crop',
  },
  {
    id: 8,
    distance: '13.1',
    name: 'Austin Half Marathon',
    location: 'Austin, TX',
    city: 'Austin',
    state: 'TX',
    month: 'Feb',
    year: '2025',
    date: 'February 16, 2025',
    time: '1:57:40',
    pace: '8:59/mi',
    place: null,
    elevation: '—',
    weather: null,
    pr: true,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1531218150217-54595bc2b934?w=400&h=300&fit=crop',
  },
  {
    id: 9,
    distance: '70.3',
    name: 'IRONMAN 70.3 Eagleman',
    location: 'Cambridge, MD',
    city: 'Cambridge',
    state: 'MD',
    month: 'Jun',
    year: '2025',
    date: 'June 8, 2025',
    time: '6:32:08',
    pace: null,
    place: null,
    elevation: '—',
    weather: null,
    pr: true,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [
      { label: 'Swim', time: '0:50:09' },
      { label: 'T1', time: '0:06:17' },
      { label: 'Bike', time: '3:15:09' },
      { label: 'T2', time: '0:07:09' },
      { label: 'Run', time: '2:13:24' },
      { label: 'Total', time: '6:32:08' },
    ],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400&h=300&fit=crop',
  },
  {
    id: 10,
    distance: '5K',
    name: 'Downtown Columbia Turkey Trot',
    location: 'Columbia, MD',
    city: 'Columbia',
    state: 'MD',
    month: 'Nov',
    year: '2025',
    date: 'November 27, 2025',
    time: '35:09',
    pace: '11:19/mi',
    place: null,
    elevation: '—',
    weather: null,
    pr: false,
    hasStrava: false,
    story: '',
    photos: [],
    gear: [],
    splits: [],
    source: 'RUNSIGNUP',
    cityPhoto: 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=400&h=300&fit=crop',
  },
]

// Stats derived from race history
export const RYAN_STATS = {
  races: 10,
  miles: 199,  // rough total: 3×6.2 + 2×13.1 + 2×26.2 + 70.3 + 2×3.1
  prs: 4,       // 10K (Sole), 26.2 (LA), 13.1 (Austin), 70.3 (Eagleman), 5K (2024 Turkey Trot)
  states: 6,    // MD, DC, CA, VA, TX, (Eagleman = MD)
}

export const RYAN_PRS = [
  { distance: '5K',      time: '28:16', color: '#1E5FA8', race: 'Downtown Columbia Turkey Trot 2024' },
  { distance: '10K',     time: '47:49', color: '#1E5FA8', race: 'Sole of the City 2021' },
  { distance: '13.1',    time: '1:57:40', color: '#1E5FA8', race: 'Austin Half Marathon 2025' },
  { distance: 'Marathon', time: '4:44:47', color: '#C9A84C', race: 'LA Marathon 2023' },
  { distance: '70.3',    time: '6:32:08', color: '#B83232', race: 'IRONMAN 70.3 Eagleman 2025' },
]

export const RYAN_GEAR = [
  { id:1, category:'Shoes', brand:'Hoka', model:'Clifton 9', color:'Black/White', url:'https://hoka.com', note:'Daily trainer' },
  { id:2, category:'Watch', brand:'Garmin', model:'Forerunner 245', color:'Black', url:'https://garmin.com', note:'' },
  { id:3, category:'Socks', brand:'Balega', model:'Hidden Comfort', color:'Black', url:'https://balega.com', note:'' },
]
