import { useNavigate } from 'react-router-dom'
import { useTheme } from '../context/ThemeContext'
import { useEffect } from 'react'

export default function Terms() {
  const navigate = useNavigate()
  const { t } = useTheme()
  const LAST_UPDATED = 'April 23, 2026'

  useEffect(() => {
    const style = document.createElement('style')
    style.id = 'rp-legal-styles'
    style.textContent = `@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Barlow:wght@300;400;500;600&family=Barlow+Condensed:wght@400;600;700&display=swap');`
    if (!document.getElementById('rp-legal-styles')) document.head.appendChild(style)
    return () => document.getElementById('rp-legal-styles')?.remove()
  }, [])

  const Section = ({ title, children }) => (
    <div style={{ marginBottom:'36px' }}>
      <h2 style={{ fontFamily:"'Bebas Neue',sans-serif", fontSize:'22px', color:t.text, letterSpacing:'1px', marginBottom:'12px' }}>{title}</h2>
      <div style={{ fontFamily:"'Barlow',sans-serif", fontSize:'15px', color:t.textMuted, lineHeight:1.8 }}>{children}</div>
    </div>
  )

  return (
    <div style={{ minHeight:'100vh', background:t.bg, transition:'background 0.25s' }}>
      <div style={{ maxWidth:'760px', margin:'0 auto', padding:'48px 24px 80px' }}>
        <button onClick={() => navigate(-1)}
          style={{ fontFamily:"'Barlow Condensed',sans-serif", fontSize:'12px', fontWeight:600, letterSpacing:'1.5px', color:'#C9A84C', background:'none', border:'none', cursor:'pointer', textTransform:'uppercase', marginBottom:'32px', padding:0 }}>
          ← Back
        </button>

        <div style={{ marginBottom:'8px', display:'flex', alignItems:'center', gap:'8px' }}>
          <div style={{ width:5, height:5, borderRadius:'50%', background:'#C9A84C' }} />
          <span style={{ fontFamily:"'Bebas Neue',sans-serif", fontSize:'10px', letterSpacing:'3px', color:t.textMuted }}>RACE PASSPORT</span>
        </div>
        <h1 style={{ fontFamily:"'Bebas Neue',sans-serif", fontSize:'48px', color:t.text, letterSpacing:'2px', marginBottom:'8px' }}>Terms of Service</h1>
        <p style={{ fontFamily:"'Barlow Condensed',sans-serif", fontSize:'13px', color:t.textMuted, marginBottom:'40px' }}>Last updated: {LAST_UPDATED}</p>

        <Section title="1. Acceptance of Terms">
          By accessing or using Race Passport ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. Race Passport is operated by Race Passport LLC ("we," "us," or "our").
        </Section>

        <Section title="2. Description of Service">
          Race Passport is a mobile-first endurance sports platform that allows users to:
          <ul style={{ marginTop:'10px', paddingLeft:'20px', display:'flex', flexDirection:'column', gap:'6px' }}>
            <li>Create a personal race passport and import race history</li>
            <li>Discover and register for endurance events</li>
            <li>Receive AI-powered coaching insights through Pacer, our AI coach</li>
            <li>Connect third-party services such as Strava</li>
            <li>Share stories and inspiration on The Wall</li>
          </ul>
        </Section>

        <Section title="3. User Accounts">
          You must create an account to use Race Passport. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information when creating your account. You must be at least 13 years old to use the Service.
        </Section>

        <Section title="4. Pacer AI Coach">
          Race Passport includes "Pacer," an AI-powered coaching feature. By using Pacer, you acknowledge and agree that:
          <ul style={{ marginTop:'10px', paddingLeft:'20px', display:'flex', flexDirection:'column', gap:'6px' }}>
            <li>Pacer's insights are generated by artificial intelligence and are for informational purposes only</li>
            <li>Pacer is not a licensed medical professional, certified coach, or sports medicine provider</li>
            <li>Pacer's recommendations should not replace advice from qualified healthcare or fitness professionals</li>
            <li>You use Pacer's insights at your own risk</li>
            <li>Pacer analyzes your race history, profile data, and connected service data (such as Strava) to generate insights</li>
          </ul>
        </Section>

        <Section title="5. User Content">
          You retain ownership of content you submit to Race Passport, including stories posted on The Wall. By submitting content, you grant Race Passport a non-exclusive, royalty-free license to display and distribute that content on the platform. You agree not to post content that is unlawful, harassing, defamatory, or unrelated to endurance sports. We reserve the right to remove content that violates these terms.
        </Section>

        <Section title="6. Third-Party Integrations">
          Race Passport integrates with third-party services including Strava and RunSignup. Your use of these integrations is subject to the respective third party's terms of service and privacy policy. Race Passport is not responsible for the practices of third-party services.
        </Section>

        <Section title="7. Race Registration">
          Race Passport facilitates discovery of races and links to registration platforms. We are not responsible for race cancellations, changes, or issues with registration through third-party platforms. Registration and participation in any race is at your own risk.
        </Section>

        <Section title="8. Intellectual Property">
          The Race Passport name, logo, design system, and Pacer AI are owned by Race Passport LLC. You may not reproduce, distribute, or create derivative works without our express written permission.
        </Section>

        <Section title="9. Disclaimers">
          The Service is provided "as is" without warranties of any kind. Race Passport does not warrant that the Service will be uninterrupted, error-free, or that AI-generated coaching insights will be accurate or suitable for your specific situation.
        </Section>

        <Section title="10. Limitation of Liability">
          To the fullest extent permitted by law, Race Passport shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to injury sustained during races discovered through our platform.
        </Section>

        <Section title="11. Changes to Terms">
          We may update these Terms of Service at any time. We will notify users of material changes by updating the "Last updated" date and, where appropriate, sending an email notification. Continued use of the Service after changes constitutes acceptance of the new terms.
        </Section>

        <Section title="12. Contact">
          <div>Questions about these terms? Contact us at <a href="mailto:legal@racepassportapp.com" style={{ color:'#C9A84C' }}>legal@racepassportapp.com</a></div>
        </Section>

      </div>
    </div>
  )
}
